version: '3.7'
services:
  #  chartmuseum:
  #    image: chartmuseum/chartmuseum:latest
  #    ports:
  #      - 18080:8080
  #    environment:
  #      - STORAGE=local
  #      - STORAGE_LOCAL_ROOTDIR=/charts
  #    volumes:
  #      - './.cache/charts:/charts'
  #  zookeeper:
  #    image: bitnami/zookeeper
  #    environment:
  #      ALLOW_ANONYMOUS_LOGIN: 'yes'
  #  kafka:
  #    image: bitnami/kafka
  #    links:
  #      - zookeeper
  #    environment:
  #      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
  #      ALLOW_PLAINTEXT_LISTENER: 'yes'
  #    ports:
  #    - 9092:9092
  rabbitmq:
    image: bitnami/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
