version: '3.7'
services:
  chartmuseum:
    image: chartmuseum/chartmuseum:latest
    ports:
      - 18080:8080
    environment:
      - STORAGE=local
      - STORAGE_LOCAL_ROOTDIR=/charts
    volumes:
      - './.cache/charts:/charts'
